# menu
menu:
  Home: .
  Crafter: crafter
  Changelog: changelog
  Download: download
  Help: categories/help  # 帮助

# Enable/Disable menu icons
menu_icons:
  enable: true  # 是否启用导航菜单图标
  home: icon-shouye
  crafter: icon-shengchan
  changelog: icon-gengxinrizhi
  download: icon-xiazai
  help: icon-bangzhu
  # archives: icon-archives-fill
  # categories: icon-folder
  # tags: icon-tags
  # repository: icon-project
  # books: icon-book-fill
  # links: icon-friendship
  # about: icon-cup-fill

# rss
rss: /atom.xml

# Site
site:
  logo:
    enabled: true
    width: 40
    height: 40
    url: ../images/logo.png
  title: xunxun.cloud # 页面title
  favicon: /favicon.png
  board: <br>有一些用户反馈过某些需求，例如多开或者自动续食物等，您是否也有类似的需求，现在填写调查问卷，您的问卷结果将会影响未来新功能的添加。<br><a href="https://www.wjx.cn/vm/mBXVUP7.aspx"><b>点我立即填写</a></b><hr><h3 class="widget-title">活动</h3>推荐返现：<br>已购用户成功推荐一名新用户购买本插件，则已购用户可获得等价于插件半价的现金奖励。<br>例如：张三在李四的推荐下花费10元购买了某插件，则李四可获得5元现金奖励。 # 站点公告
  copyright: false # 底部版权信息

# config
config:
  skin: theme-black  # 主题颜色 theme-black theme-blue theme-green theme-purple
  layout: main-center # 布局方式 main-left main-center main-right
  toc: true # 是否开启文章章节目录导航
  menu_highlight: true # 是否开启当前菜单高亮显示
  thumbnail: false # enable posts thumbnail, options: true, false
  # excerpt_link: Read More
  #New
  isNewTabLinks: false #是否链接打开新标签页
  autoUnfold: false # 默认展开文章目录

# Pagination
pagination:
  number: false
  prev: 
    alwayShow: true
  next:
    alwayShow: true
  midSize: 2 # 当前页码左右到省略号显示的页码数，默认2，表现为 1 ... 4 5 6 7 8 ... 10
  showContent: true # 页面文章小于2篇时显示文章内容

# Sidebar
sidebar: right
widgets:
  - board  
  # - category
  # - tag
  # - tagcloud
  # - archive
  # - recent_posts

# display widgets at the bottom of index pages (pagination == 2)
index_widgets:
# - category
# - tagcloud
# - archive  

# widget behavior
archive_type: 'monthly'
show_count: true

# Fancybox
fancybox: false

# Search
search:
  insight: true # you need to install `hexo-generator-json-content` before using Insight Search
  baidu: false # you need to disable other search engines to use Baidu search

# Donate
donate:
  enable: false
  # 微信打赏
  wechatpay:
    qrcode: images/donate/wechatpayimg.png
    title: 微信支付
  # 支付宝打赏
  alipay: 
    qrcode: images/donate/alipayimg.png 
    title: 支付宝

# Share
# weibo,qq,qzone,wechat,tencent,douban,diandian,facebook,twitter,google,linkedin
share:
  enable: false  # 是否启用分享
  sites: weibo,qq,wechat,facebook,twitter  # PC端显示的分享图标
  mobile_sites: weibo,qq,qzone  # 移动端显示的分享图标

# Github
# github: 
#   username: xun-xh  # github username

# Repository Info (This will override 'github' option)
# 项目仓库信息（将会覆盖 github 项）
repository:
  platform: github # 托管平台（github | gitee）
  username: xun-xh # 用户名

# Comment
# Gitment
# Introduction: https://imsun.net/posts/gitment-introduction/
comment:
  type: valine  # 启用哪种评论系统
  disqus:  # enter disqus shortname here
  youyan: 
    uid: 1783844 # enter youyan uid 
  livere:
    uid: # enter youyan uid 
  gitment:
    githubID: 
    repo: 
    ClientID: 
    ClientSecret: 
    lazy: false
  gitalk: # gitalk. https://gitalk.github.io/
    owner:  #必须. GitHub repository 所有者，可以是个人或者组织。
    admin:  #必须. GitHub repository 的所有者和合作者 (对这个 repository 有写权限的用户)。
    repo:  #必须. GitHub repository.
    ClientID:  #必须. GitHub Application Client ID.
    ClientSecret:  #必须. GitHub Application Client Secret.
    enableHotKey: true
    language: zh-CN
    
  valine: # Valine. https://valine.js.org
    appid:  # your leancloud application appid
    appkey:  # your leancloud application appkey
    notify: false # mail notifier , https://github.com/xCss/Valine/wiki
    verify: false # Verification code
    placeholder: Just go go # comment box placeholder
    avatar: mm # gravatar style
    meta: nick,mail,link # custom comment header
    pageSize: 10 # pagination size
    visitor: false # Article reading statistic https://valine.js.org/visitor.html
douban:
  user: # 豆瓣用户名
  start: 0 # 从哪一条记录开始
  count: 100 # 获取豆瓣书单数据条数
  apikey: # 豆瓣apikey
  
# PV
pv:
  busuanzi:
    enable: false  # 不蒜子统计
  leancloud:
    enable: false  # leancloud统计
    app_id: # leancloud <AppID>
    app_key: # leancloud <AppKey>
        
# wordcount
postCount:
  enable: false
  wordcount: true  # 文章字数统计
  min2read: true  # 阅读时长预计 

# Plugins
plugins:
  google_analytics: # enter the tracking ID for your Google Analytics
  google_site_verification: # enter Google site verification code
  baidu_analytics: # enter Baidu Analytics hash key
  tencent_analytics: 
  
# Miscellaneous
twitter:
google_plus:
fb_admins:
fb_app_id:  
  
# profile
profile:
  enabled: false # Whether to show profile bar
  articleSelfBlock: true # 关闭文章下方的自我介绍
  avatar: images/avatar.jpg
  gravatar: # Gravatar email address, if you enable Gravatar, your avatar config will be overriden
  author: 昵称
  author_title: Web Developer & Designer
  author_description: 个人简介。
  location: Shenzhen, China
  follow: https://github.com/xun-xh
  # Social Links
  social:
    links:
      github: https://github.com/xun-xh
      qq: http://wpa.qq.com/msgrd?v=3&uin=1072870487&site=qq&menu=yes
      # weibo: http://weibo.com/xun-xh
      # twitter: https://twitter.com/iwebued
      # facebook: /
      # dribbble: /
      # behance: https://www.behance.net/xun-xh
      # rss: atom.xml
    link_tooltip: true # enable the social link tooltip, options: true, false
  # My Skills 
  skills:
    Git: ★★★☆☆
    Gulp: ★★★☆☆
    Javascript: ★★★☆☆
    HTML+CSS: ★★★☆☆
    Bootstrap: ★★★☆☆
    ThinkPHP: ★★★☆☆
    平面设计: ★★★☆☆
  # My Personal Links
  links:
    Github: https://github.com/xun-xh
    Blog: http://www.xunxun.cloud
    微博: http://weibo.com/xun-xh
    花瓣: http://huaban.com/xun-xh
    Behance: https://www.behance.net/xun-xh
  # My Personal Labels
  labels:
    - 前端
    - 前端开发
    - 前端重构
    - Web前端
    - 网页重构
  # My Personal Works
  works:
    name:
      link: http://www.xunxun.cloud
      date: 2016
  # My Personal Projects
  projects:
    cofess/gulp-startpro: https://github.com/xun-xh/gulp-startpro
    cofess/hexo-theme-pure: https://github.com/xun-xh/hexo-theme-pure
 
  auto_excerpt:
    enable: true
    length: 150